version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
        - ~/mysql-build/datadir:/var/lib/mysql
        - ~/mysql-build/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    restart: always
    ports:
      - 26666:80